[[clients]]
handle = "Anton"
port = 5000

[[clients]]
handle = "Alice"
port = 5001

[[clients]]
handle = "Bob"
port = 5002

[[clients]]
handle = "clear"
port = 5003

[defaults]
whoisport = 4000
autoreply = "Ich bin nicht da."
imagepath = "bilder/"
port_range = [ 5000, 5100,]
